### ISSUE TITLE
The following bug appears when the code follows razor

### ISSUE THREAD

**Issue by WileyChia** [TwentyFourMinutes/RazorMinifier#2] opened 2019-12-15 12:12 UTC
Look picture, you will understand
![image](https://user-images.githubusercontent.com/43943792/70862363-676cb180-1f76-11ea-9f96-f610a0fbde07.png)

RazorMinifier doesn't work after this problem. I'm not sure if it's caused by this problem.

Poor English , Please forgive me if I have grammar mistakes

**Comment by TwentyFourMinutes** [comment] 2019-12-16 14:42
Well did you get any crash-report by Visual Studio?
If so share the error itself please.

If there isn't any error itself, try to describe your problem in more detail.

**Comment by WileyChia** [comment] 2019-12-17 10:09
It streamlines the space between the text and the razor statement as it processes the code.

You can find that there is no space between AAA and @ HTML in the two sentence code of the picture in my question. At this time, NETCORE recognizes it as plain text instead of razor code.

![image](https://user-images.githubusercontent.com/43943792/70985571-4ed7d500-20f7-11ea-836c-d6c42353d254.png)

Razorminifier did stop working, but now I can't reproduce it, but it's not related to the above problem.

**Comment by TwentyFourMinutes** [comment] 2019-12-17 11:24
I think I know what the issue is what you are facing, I'll work on a fix later.

Also if you think `RazorMinifier` stopped working try to restart Visual Studio and if it still doesn't work, create a new issue.

**Comment by TwentyFourMinutes** [comment] 2019-12-17 12:57
Should now be fixed with commit 16a91f6696d60ef9e7e938d8ee902cf735b11f2d, please update the extension to [> v1.4](https://github.com/TwentyFourMinutes/RazorMinifier/releases/)!

**Closed as completed by TwentyFourMinutes** 2019-12-17 12:57 UTC
Labels: bug
